### PR TITLE
Pdf on page

### LINKED ISSUE #50: Display resumes in-site
Create a react component that, given a Word doc or PDF file, can display it in-site. This component should also allow for downloading the document.

This component should be used in two locations:
1) As a pop-up dialog when you click on "view resume" in search results, populated with the resume of the selected employee
2) As a card in the "Your Resume" section that displays the logged-in employee's resume

### PR DESCRIPTION
**Pull request by sean-hale-dev**
Closes #50 

This should display the documents using the `react-doc-viewer`. 

Due to the nature of rendering doc/docx this actually relies on the ec2 instance so if you're experiencing infinite loading or an error page check with @sean-hale-dev.

I also updated the `server.js` endpoints to use a `endpoint_prefix` variable set to `/api` which was for deployment consistency.

Finally I removed all unused-imports and changed `==` and `!=` to `===` and `!==` to resolve compilation warnings.

### CODE REVIEW

**Comment by technostarbtd5** [comment]
Bug I found: docx-type files don't appear to support resume downloading (check out BrentN1's file).
Code style thingy: You should probably refactor the resume viewer dialog to be its own separate component in the components/shared folder. If you use the same code twice, write it once! This way, any bugfixes just need to be done once as well.

**Comment by sean-hale-dev** [comment]
Migrated the dialog code into a shared component and added a download resume button which handles downloading for all file types with correct extensions

**Comment by technostarbtd5** [comment]
Issues have been successfully fixed.

**Review by technostarbtd5 — APPROVED** [review]
Appears to work as described. Resume download not broken. Style appears good.

**Pull request merged**
